/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.streetferret.crudo;

import com.onthegomap.planetiler.Planetiler;
import com.onthegomap.planetiler.config.Arguments;
import java.nio.file.Path;

public class CrudoGenerator {
  public static void main(String... args) throws Exception {
    run(Arguments.fromArgsOrConfigFile(args));
  }

  static void run(Arguments args) throws Exception {
    var dataDir = Path.of("data");
    var sourcesDir = dataDir.resolve("sources");

    var area = args.getString(
      "area",
      "name of the extract to download if osm_url/osm_path not specified (i.e. 'monaco' 'rhode island' 'australia' or 'planet')",
      "monaco"
    );

    var planetiler = Planetiler.create(args)
      .addShapefileSource("water",
        sourcesDir.resolve("water-polygons-split-3857.zip"),
        "https://osmdata.openstreetmap.de/download/water-polygons-split-3857.zip")
      .addOsmSource("osm",
        sourcesDir.resolve(area.replaceAll("[^a-zA-Z]+", "_") + ".osm.pbf"),
        "planet".equalsIgnoreCase(area) ? ("aws:latest") : ("geofabrik:" + area))
      .setProfile(new CrudoProfile());

    planetiler.overwriteOutput("mbtiles", Path.of("data", "crudo.mbtiles"))
      .run();
  }
}
